---
kind: pipeline
type: docker
name: deploy Handbrake (prod)

steps:
  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:2.13
    settings:
      galaxy: .ansible/roles/requirements.yaml
      inventory: .ansible/inventories/prod.yaml
      playbook: .ansible/deploy.yaml
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - push
  branch:
    - stable

...
