version: '3.8'
services: 

  webui:
    image: zocker160/handbrake-nvenc:latest
    environment:
      # global options
      - KEEP_APP_RUNNING=1
      - ENABLE_CJK_FONT=1

      # watch (plex)
      - AUTOMATED_CONVERSION_PRESET={{ automated_conversion_preset }}
      - AUTOMATED_CONVERSION_FORMAT=mkv
      - AUTOMATED_CONVERSION_KEEP_SOURCE=1
      - AUTOMATED_CONVERSION_OVERWRITE_OUTPUT=1
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=plex

      # watch2 (discord)
      - AUTOMATED_CONVERSION_PRESET_2=Web/Discord Small 2 Minutes 360p30
      - AUTOMATED_CONVERSION_FORMAT_2=m4v
      - AUTOMATED_CONVERSION_KEEP_SOURCE_2=1
      - AUTOMATED_CONVERSION_OVERWRITE_OUTPUT_2=1
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR_2=discord

      # nvidia-gpu
      - NVIDIA_DRIVER_CAPABILITIES=video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /etc/localtime:/etc/localtime
      - {{ config_dir }}:/storage/presets:ro
      - nas-blu-ray:/storage/blu-ray:ro
      - {{ data_dir }}:/config:rw
      - nas-handbrake-watch-plex:/watch:rw
      - nas-handbrake-watch-discord:/watch2:rw
      - nas-handbrake-output:/output:rw
    networks:
      - {{ traefik_network }}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ repository }}.loadbalancer.server.port=5800
        - traefik.http.routers.{{ repository }}.rule=Host(`{{ host }}`)
        - traefik.http.routers.{{ repository }}.service={{ repository }}
        - traefik.http.routers.{{ repository }}.tls.certresolver=step-ca
      resources:
        limits:
          cpus: '6.0'
          memory: 2G


volumes:
  # NFS volumes requires `nfs-common` on Debian
  # OR `nfs-client` on CentOS/Fedora
  nas-blu-ray:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ nfs_host }},ro,nfsvers=4,async
      device: :{{ nfs_roms_path }}/Blu-ray

  nas-handbrake-watch-plex:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ nfs_host }},rw,nfsvers=4,async
      device: :{{ nfs_handbrake_path }}/watch/plex

  nas-handbrake-watch-discord:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ nfs_host }},rw,nfsvers=4,async
      device: :{{ nfs_handbrake_path }}/watch/discord

  nas-handbrake-output:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ nfs_host }},rw,nfsvers=4,async
      device: :{{ nfs_handbrake_path }}/output


networks:
  {{ traefik_network }}:
    external: true
    name: {{ traefik_network }}
