- hosts: handbrake
  roles:
    - common
    - traefik

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - include_role:
        name: common
        tasks_from: make_data_dir

    - name: 'Create subdirectories under {{ data_dir }}'
      file:
        state: directory
        path: '{{ data_dir }}/{{ sub_dir }}'
      loop:
        - config
        - watch
        - output
      loop_control:
        loop_var: sub_dir

    - include_role:
        name: docker
        tasks_from: stack_deploy
      vars:
        docker_compose_template: docker-compose.yaml.j2
