- hosts: swarm_manager
  roles:
    - application
    - traefik

  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir

    - include_role:
        name: application
        tasks_from: make_data_dir

    - name: 'Create subdirectories under {{ data_dir }}'
      file:
        state: directory
        path: '{{ data_dir }}/{{ sub_dir }}'
      loop:
        - config
        - watch
        - output
      loop_control:
        loop_var: sub_dir

    - name: 'Copy custom handbrake presets into {{ config_dir }}'
      copy:
        src: '{{ playbook_dir }}/../presets/'
        dest: '{{ config_dir }}' 

    - include_role:
        name: docker
        tasks_from: stack_deploy
